### ISSUE TITLE
Displaying contacts offline where precise “last-seen” data is available

### ISSUE THREAD

**Issue by nomeata** [majn/telegram-purple#134]
I’m not a very long user of telegram, so this might be wrong...

It seems that if you allow telegram to give way your own “last seen” data precisely, you also get that information for the other parties. If this data is available, it seems to make sense to display the contact as offline much quicker than a timespan measured in days, as the current configuration seems to allow.

**Comment by BenWiederhake** [comment]
Good point.

However, it seems that this isn't the case with the current version anymore. One of my contacts is "Last seen: 38 mins\nStatus: Offline" with the correct symbol for "offline".

So maybe this is already fixed ... *calls* majn?

**Comment by nomeata** [comment]
Right, I see that for two of my contacts as well. The other is shown as online, last seen a month ago (which was before I started using telegram-purple, if that matters.) Looks not fixed, but rather very weird :-)

**Comment by majn** [comment]
So basically you want a more fine-grained setting?

**Comment by nomeata** [comment]
On a very high level, I want only online contacts to be displayed as online. Right now it displays someone as online where it says “last seen online one month ago”.

Maybe the reason is that telegram reports only approximate last-seen-times, for those contacts where do not share my presence either, and simply does not understand such times?

**Comment by 0nse** [comment]
The plugin is already able to tell when a person is online, which is indicated by the lack of the mobile phone symbol in a chat. Wouldn't it make sense to show only these people as 'online', other people as 'away' and those, who weren't online for days as 'offline' (as is already done)?

**Comment by pseudomonas** [comment]
I can't quite figure out what "online" is supposed to convey in the interface. For those contacts who are sharing their online-state, surely they should be marked as online if-and-only-if they're actually online?
